version: '3'

services:
  goapp:
    container_name: goapp
    # REF: https://qiita.com/mk-tool/items/1c7e4929055bb3b7aeda
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    tty: true
    ports:
      - 8888:80
    volumes:
      - ./:/go/src/app
